
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: iswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: iswebapp
        service: webapp
    spec:
      containers:
        - name: webapp
          image: core-nexus.dev.tedo.ru:18443/webapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: iswebapp
    service: webapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: iswebapp